#!/bin/bash

# This script aims to be a bootstrap script for bringing up
# a work station for essence employee.

die() {
	echo >&2 "$@"
	exit 1
}

## Generate ssh key pair
ssh_private_key="$HOME/.ssh/id_rsa"
if ! [ -f "$ssh_private_key" ]; then
	ssh-keygen -t rsa -f "$ssh_private_key" -N ''
fi

# Install ansible
sudo apt update
sudo apt install ansible --assume-yes

echo "I: Now make sure to copy ssh public key to TFS"
echo "   Then run: 'ansible-playbook --ask-become-pass esi-bringup.yml'"

