---

- name: Set up linux work station
  connection: local
  hosts: 127.0.0.1
  gather_facts: false
  vars:
    gitdir: "{{ lookup('env','HOME') }}/git"
    fullname: Omer Dagan
    email: "{{ lookup('env', 'USER') }}@essence-grp.com"

  tasks:
  - name: Add IP address for essence hosts 
    lineinfile:
      dest: /etc/hosts
      regexp: '172.16.0.139\s+es-tfs01-il$'
      line: '172.16.0.139 es-tfs01-il'
      state: present
    become: yes

  - name: Add preferences to .vimrc
    lineinfile:
      dest: "$HOME/.vimrc"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: yes
    loop:
      - { regexp: 'colorscheme\s+.*', line: 'colorscheme darkblue' }
      - { regexp: 'set\s+(no)?number', line: 'set number' }

  - name: Add environment variables to ~/.profile
    lineinfile:
      dest: $HOME/.profile
      line: "export {{ item }}"
      state: present
    with_items:
      - 'FULLNAME="{{ fullname }}"'
      - 'EMAIL="{{ email }}"'
      - EDITOR=vim

  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - openssh-server
      - git
      - make
      - autoconf
      - automake
      - libtool
      - debhelper
      - build-essential
      - dput
      - ccache
    become: yes
 
  - name: Configure git
    git_config:
      name: "{{ item.name }}"
      scope: "{{ item.scope }}"
      value: "{{ item.value }}"
    loop:
      - { name: 'user.name', scope: 'global', value: "{{ fullname }}" }
      - { name: 'user.email', scope: 'global', value: "{{ email }}" }
      - { name: 'alias.lola', scope: 'global', value: "log --graph --decorate --pretty=oneline --abbrev-commit --all" }
      - { name: 'alias.lol', scope: 'global', value: "log --graph --decorate --pretty=oneline --abbrev-commit" }
      - { name: 'alias.lolau', scope: 'global', value: "log --graph --decorate --pretty=format:\"%C(yellow)%h %C(green bold)%d %C(blue)%an %Creset%s\" --abbrev-commit" }
      - { name: 'alias.unstage', scope: 'global', value: "reset HEAD --" }
      - { name: 'alias.difftoolcommit', scope: 'global', value: '!sh -c "git difftool $1^1..$1" -' }
      - { name: 'alias.subup', scope: 'global', value: "submodule update --recursive" }
      - { name: 'alias.last', scope: 'global', value: "log -1 --name-status" }
      - { name: 'diff.tool', scope: 'global', value: "vimdiff" }
      - { name: 'merge.tool', scope: 'global', value: "vimdiff" }
      - { name: 'difftool.prompt', scope: 'global', value: "false" }
 
  - name: Copy git prompt shell file
    copy:
      src: gitprompt.sh
      dest: "{{ lookup('env','HOME') }}/.gitprompt.sh"
      force: false
      mode: 0644

  - name: Source git prompt from .bashrc
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      regexp: '\s*\[ -f \$HOME/.gitprompt \] && . \$HOME/.gitprompt\s*'
      line: '[ -f $HOME/.gitprompt.sh ] && . $HOME/.gitprompt.sh'
 
  - name: Add bash aliases
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.bash_aliases"
      line: '{{ item }}'
      state: present
      create: true
    with_items:
      - 'alias cdgit="cd {{ gitdir }}"'
      - 'alias cdvf4="cd {{ gitdir }}/VF4_Linux"'
      - "alias cdmem=\"cd {{ lookup('env','HOME') }}/memorize\""
  
  - name: Create directory for git repositories
    file:
      path: "{{ gitdir }}"
      state: directory

  - name: Add Essence tfs (git) machines to known hosts
    shell: "if ssh-keygen -F {{ item }} >/dev/null; then echo 'unchanged'; else ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts; echo changed; fi"
    register: known_hosts_changed
    changed_when: known_hosts_changed.stdout == "changed"
    with_list:
      - es-tfs01-il
      - es-tfs01-il.essencesecurity.com
 
  - name: Clone opt/telit
    git:
      repo: "ssh://es-tfs01-il:22/tfs/EssenceCollection/SecuritasDirect/_git/telit"
      dest: "/opt/telit"
      recursive: yes
 
  - name: Clone repositories
    git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
      recursive: yes
    loop:
      - { repo: 'ssh://es-tfs01-il:22/tfs/EssenceCollection/SecuritasDirect/_git/VF4_Linux', dest: '{{ gitdir }}/VF4_Linux' }
      - { repo: 'ssh://es-tfs01-il:22/tfs/EssenceCollection/SecuritasDirect/_git/open_source', dest: '{{ gitdir }}/open_source' }
