---

- name: Set up linux work station
  hosts: nodes
  gather_facts: false
  vars:
    gitdir: "{{ lookup('env','HOME') }}/git"
    fullname: Omer Dagan
    email: "{{ lookup('env', 'USER') }}@essence-grp.com"

  tasks:
  - name: Add IP address for essence hosts 
    lineinfile:
      dest: /etc/hosts
      regexp: '172.16.0.139\s+es-tfs01-il$'
      line: '172.16.0.139 es-tfs01-il'
      state: present
    become: yes

  - name: Add environment variables to ~/.profile
    lineinfile:
      dest: $HOME/.profile
      line: "export {{ item }}"
      state: present
    with_items:
      - 'FULLNAME="{{ fullname }}"'
      - 'EMAIL="{{ email }}"'
      - EDITOR=vim

  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install required packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - openssh-server
      - konsole
      - vim
      - vim-airline
      - vim-airline-themes
      - vim-fugitive
      - vim-syntastic
      - git
      - make
      - autoconf
      - automake
      - libtool
      - debhelper
      - build-essential
      - dput
      - ccache
      - fastboot
      - ctags
    become: yes

  - name: Add needed groups to user
    user:
      name: "{{ lookup('env', 'USER') }}"
      shell: /bin/bash
      groups: sudo,adm,users,plugdev,dialout
      append: yes
    become: yes

  - name: Add udev config needed to access adb devuces
    copy:
      dest: /etc/udev/rules.d/51-android.rules
      content: |
        SUBSYSTEM=="usb", ATTR{idVendor}=="1bc7", MODE="0666", GROUP="plugdev"
        SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", MODE="0666", GROUP="plugdev"
        SUBSYSTEM=="usb", ATTR{idVendor}=="2c7c", MODE="0666", GROUP="plugdev"
    become: yes
 
  - name: Configure git
    git_config:
      name: "{{ item.name }}"
      scope: "{{ item.scope }}"
      value: "{{ item.value }}"
    loop:
      - { name: 'user.name', scope: 'global', value: "{{ fullname }}" }
      - { name: 'user.email', scope: 'global', value: "{{ email }}" }
      - { name: 'alias.lola', scope: 'global', value: "log --graph --decorate --pretty=oneline --abbrev-commit --all" }
      - { name: 'alias.lol', scope: 'global', value: "log --graph --decorate --pretty=oneline --abbrev-commit" }
      - { name: 'alias.lolau', scope: 'global', value: "log --graph --decorate --pretty=format:\"%C(yellow)%h %C(green bold)%d %C(blue)%an %Creset%s\" --abbrev-commit" }
      - { name: 'alias.unstage', scope: 'global', value: "reset HEAD --" }
      - { name: 'alias.difftoolcommit', scope: 'global', value: '!sh -c "git difftool $1^1..$1" -' }
      - { name: 'alias.subup', scope: 'global', value: "submodule update --recursive" }
      - { name: 'alias.last', scope: 'global', value: "log -1 --name-status" }
      - { name: 'diff.tool', scope: 'global', value: "vimdiff" }
      - { name: 'merge.tool', scope: 'global', value: "vimdiff" }
      - { name: 'difftool.prompt', scope: 'global', value: "false" }
 
  - name: Copy git prompt shell file
    copy:
      src: "{{ item.source }}"
      dest: "{{ item.dest }}"
      force: "{{ item.force }}"
      mode: 0644
    loop:
        - { source: '../srcfiles/gitprompt.sh', dest: "{{ lookup('env','HOME') }}/.gitprompt.sh", force: true}
        - { source: '../srcfiles/vimrc', dest: "{{ lookup('env','HOME') }}/.vimrc", force: flase }

  - name: Source git prompt from .bashrc
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      regexp: '\s*\[ -f \$HOME/.gitprompt \] && . \$HOME/.gitprompt\s*'
      line: '[ -f $HOME/.gitprompt.sh ] && . $HOME/.gitprompt.sh'
 
  - name: Add bash aliases
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.bash_aliases"
      line: '{{ item }}'
      state: present
      create: true
    with_items:
      - 'alias cdgit="cd {{ gitdir }}"'
      - 'alias cdvf4="cd {{ gitdir }}/VF4_Linux"'
      - "alias cdmem=\"cd {{ lookup('env','HOME') }}/memorize\""
  
  - name: Create directory for git repositories
    file:
      path: "{{ gitdir }}"
      state: directory

  - name: Add Essence tfs (git) machines to known hosts
    shell: "if ssh-keygen -F {{ item }} >/dev/null; then echo 'unchanged'; else ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts; echo changed; fi"
    register: known_hosts_changed
    changed_when: known_hosts_changed.stdout == "changed"
    with_list:
      - es-tfs01-il
      - es-tfs01-il.essencesecurity.com

  - name: Check if vscode is installed
    command: dpkg-query -W code
    register: vscode_check_deb
    failed_when: vscode_check_deb.rc > 1
    changed_when: vscode_check_deb.rc == 1

  - name: Download vscode
    get_url:
      url=https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest="{{ lookup('env','HOME') }}/Downloads/vscode.deb"
    when: vscode_check_deb.rc == 1

  - name: Install vscode
    apt: deb="{{ lookup('env','HOME') }}/Downloads/vscode.deb"
    when: vscode_check_deb.rc == 1
    sudo: true
    become: yes

  - name: Add pathogen plugin manager to vim
    get_url:
      url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
      dest: "{{ lookup('env','HOME') }}/.vim/autoload/pathogen.vim"
      mode: 664
      force: no

  - name: Clone youCompleteMe vim addon
    git:
      repo: https://github.com/ycm-core/YouCompleteMe.git
      dest: "{{ lookup('env','HOME') }}/.vim/bundle/youcompleteme"
      version: origin/legacy-vim

  - name: Update youcompleteme submodules
    shell:
      cmd: git submodule update --init --recursive
      chdir: "{{ lookup('env','HOME') }}/.vim/bundle/youcompleteme"

  - name: Install youcomplete me vim addon for c/cpp only
    shell:
      cmd: python3 install.py --clangd-completer
      chdir: "{{ lookup('env','HOME') }}/.vim/bundle/youcompleteme"
 
