---

- name: Set up linux work station
  hosts: nodes
  gather_facts: false
  vars:
    gitdir: "{{ lookup('env','HOME') }}/git"
    fullname: Omer Dagan
    email: "mr.omer.dagan@gmail.com"

  tasks:
  - name: Add environment variables to ~/.profile
    lineinfile:
      dest: $HOME/.profile
      line: "export {{ item }}"
      state: present
    with_items:
      - 'FULLNAME="{{ fullname }}"'
      - 'EMAIL="{{ email }}"'
      - EDITOR=vim

  - name: Update apt cache
    apt:
      update_cache: yes
    become: yes

  - name: Install Debian packages
    apt:
      pkg:
        - apache2
        - autoconf
        - automake
        - build-essential
        - ccache
        - cmake
        - exuberant-ctags
        - curl
        - cppman
        - cscope
        - debhelper
        - devscripts
        - dput
        - dh-make
        - dh-python
        - docker
        - docker.io
        - fakeroot
        - g++
        - git
        - gpg
        - jq
        - konsole
        - lynx
        - lsb-release
        - make
        - markdown
        - mosquitto
        - mosquitto-clients
        - openssh-server
        - perl
        - perl-doc
        - pkg-config
        - python
        - python3
        - pylint3
        - screen
        - shellcheck
        - sqlite3
        - taskwarrior
        - tree
        - uuid-dev
        - vim
        - vim-airline
        - vim-airline-themes
        - vim-fugitive
        - vim-python-jedi
        - vim-syntastic
      state: present
    become: yes

  - name: Add needed groups to user
    user:
      name: "{{ lookup('env', 'USER') }}"
      shell: /bin/bash
      groups: sudo,adm,users
      append: yes
    become: yes

  - name: Configure git
    git_config:
      name: "{{ item.name }}"
      scope: "{{ item.scope }}"
      value: "{{ item.value }}"
    loop:
      - { name: 'user.name', scope: 'global', value: "{{ fullname }}" }
      - { name: 'user.email', scope: 'global', value: "{{ email }}" }
      - { name: 'alias.lola', scope: 'global', value: "log --graph --decorate --pretty=oneline --abbrev-commit --all" }
      - { name: 'alias.lol', scope: 'global', value: "log --graph --pretty=format:'%C(auto)%h%d (%cr) %C(blue bold)%an  %Creset%s'" }
      - { name: 'alias.unstage', scope: 'global', value: "reset HEAD --" }
      - { name: 'alias.difftoolcommit', scope: 'global', value: '!sh -c "git difftool $1^1..$1" -' }
      - { name: 'alias.subup', scope: 'global', value: "submodule update --recursive" }
      - { name: 'alias.last', scope: 'global', value: "log -1 --name-status" }
      - { name: 'alias.lastm', scope: 'global', value: '!sh -c "git log -$1 --name-status"' }
      - { name: 'diff.tool', scope: 'global', value: "vimdiff" }
      - { name: 'merge.tool', scope: 'global', value: "vimdiff" }
      - { name: 'difftool.prompt', scope: 'global', value: "false" }
 
  - name: Copy customization scripts (git prompt, vimrc, bash_aliases)
    copy:
      src: "{{ item.source }}"
      dest: "{{ item.dest }}"
      force: "{{ item.force }}"
      mode: 0644
    loop:
        - { source: '../srcfiles/gitprompt.sh', dest: "{{ lookup('env','HOME') }}/.gitprompt.sh", force: true}
        - { source: '../srcfiles/vimrc', dest: "{{ lookup('env','HOME') }}/.vimrc", force: false }
        - { source: '../srcfiles/bash_aliases', dest: "{{ lookup('env','HOME') }}/.bash_aliases", force: false }

  - name: Source git prompt from .bashrc
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      regexp: '\s*\[ -f \$HOME/.gitprompt \] && . \$HOME/.gitprompt\s*'
      line: '[ -f $HOME/.gitprompt.sh ] && . $HOME/.gitprompt.sh'

  - name: Create directory for git repositories
    file:
      path: "{{ gitdir }}"
      state: directory

  - name: Create vim plugins directories
    file:
      path: "{{ lookup('env','HOME') }}/.vim/autoload"
      state: directory
    with_items:
      - "{{ lookup('env','HOME') }}/.vim/autoload"
      - "{{ lookup('env','HOME') }}/.vim/bundle"

  - name: Add pathogen plugin manager to vim
    get_url:
      url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
      dest: "{{ lookup('env','HOME') }}/.vim/autoload/pathogen.vim"
      mode: 0664
      force: no

  - name: Clone youCompleteMe vim addon
    git:
      repo: https://github.com/ycm-core/YouCompleteMe.git
      dest: "{{ lookup('env','HOME') }}/.vim/bundle/youcompleteme"
      version: origin/legacy-vim

  - name: Update youcompleteme submodules
    shell:
      cmd: git submodule update --init --recursive
      chdir: "{{ lookup('env','HOME') }}/.vim/bundle/youcompleteme"

  - name: Install youcomplete me vim addon for c/cpp only
    shell:
      cmd: python3 install.py --clangd-completer
      chdir: "{{ lookup('env','HOME') }}/.vim/bundle/youcompleteme"
 
